### ISSUE TITLE
Failed to load the dart-tools package

### ISSUE THREAD

**Issue by davisnrjr** [radicaled/dart-tools#102]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.0 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [dart-tools](https://github.com/radicaled/dart-tools) package 0.9.23

### Stack Trace

Failed to load the dart-tools package

```
At Duplicate key 'atom-text-editor'

Error: Duplicate key 'atom-text-editor'
  at Object.detectDuplicateKeys (/app.asar/node_modules/season/lib/cson.js:268:13)
  at /app.asar/node_modules/cson-parser/lib/parse.js:115:38
  at Array.reduce (native)
  at Obj (/app.asar/node_modules/cson-parser/lib/parse.js:107:30)
  at transformNode (/app.asar/node_modules/cson-parser/lib/parse.js:197:12)
  at Value (/app.asar/node_modules/cson-parser/lib/parse.js:79:14)
  at transformNode (/app.asar/node_modules/cson-parser/lib/parse.js:197:12)
  at Block (/app.asar/node_modules/cson-parser/lib/parse.js:76:14)
  at transformNode (/app.asar/node_modules/cson-parser/lib/parse.js:197:12)
  at Object.parse (/app.asar/node_modules/cson-parser/lib/parse.js:203:12)
  at parseObject (/app.asar/node_modules/season/lib/cson.js:42:23)
  at parseContentsSync (/app.asar/node_modules/season/lib/cson.js:68:16)
  at Object.readFileSync (/app.asar/node_modules/season/lib/cson.js:170:14)
  at /app.asar/src/package.js:439:38
  at Array.map (native)
  at Package.module.exports.Package.loadKeymaps (/app.asar/src/package.js:436:46)
  at /app.asar/src/package.js:114:19
  at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
  at Package.module.exports.Package.load (/app.asar/src/package.js:110:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/app.asar/src/package-manager.js:468:14)
  at /app.asar/src/package-manager.js:412:19
  at Config.module.exports.Config.transact (/app.asar/src/config.js:312:16)
  at PackageManager.module.exports.PackageManager.loadPackages (/app.asar/src/package-manager.js:407:19)
  at /app.asar/src/atom-environment.js:794:28

```

### Commands

```
  3x -0:10.9.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always)
     -0:10.6.0 flutter:enable (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-toolbar 0.1.6 
dart-tools 0.9.23 
dartlang 0.6.45 
flutter 0.2.6 
linter 1.11.21 
synced-sidebar 0.4.3 
```

**Comment by radicaled** [comment]
Package is unmaintained, recommend https://atom.io/packages/dartlang
