### ISSUE TITLE
Failed to activate the dart-tools package

### ISSUE THREAD

**Issue by hectorfhurtado** [radicaled/dart-tools#26]
Hi, this is the stacktrace on my Windows machine:

[Enter steps to reproduce below:]

1. Intall
2. Wait for red message showing the stacktrace

**Atom Version**: 0.199.0
**System**: Windows 7
**Thrown From**: [dart-tools](https://github.com/radicaled/dart-tools) package, v0.9.2

### Stack Trace

Failed to activate the dart-tools package

```
At Failed to execute 'registerElement' on 'Document': Registration failed for type 'dart-tools-problem-view'. A type with that name is already registered.

Error: Failed to execute 'registerElement' on 'Document': Registration failed for type 'dart-tools-problem-view'. A type with that name is already registered.
  at Error (native)
  at Function.ProblemView.register (C:\Users\hector.hurtado\.atom\packages\dart-tools\lib\info\problem_view.coffee:9:20)
  at Object.module.exports.activate (C:\Users\hector.hurtado\.atom\packages\dart-tools\lib\dart-tools.coffee:62:17)
  at Package.module.exports.Package.activateNow (C:\Users\hector.hurtado\AppData\Local\atom\app-0.199.0\resources\app.asar\src\package.js:238:19)
  at C:\Users\hector.hurtado\AppData\Local\atom\app-0.199.0\resources\app.asar\src\package.js:219:30
  at Package.module.exports.Package.measure (C:\Users\hector.hurtado\AppData\Local\atom\app-0.199.0\resources\app.asar\src\package.js:163:15)
  at Package.module.exports.Package.activate (C:\Users\hector.hurtado\AppData\Local\atom\app-0.199.0\resources\app.asar\src\package.js:211:14)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\hector.hurtado\AppData\Local\atom\app-0.199.0\resources\app.asar\src\package-manager.js:435:21)
  at C:\Users\hector.hurtado\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:345:29
  at exit (C:\Users\hector.hurtado\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:41:16)
  at triggerExitCallback (C:\Users\hector.hurtado\AppData\Local\atom\app-0.199.0\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (C:\Users\hector.hurtado\AppData\Local\atom\app-0.199.0\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```

### Commands

```
     -3:31.4.0 settings-view:open (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "followSymlinks": true,
    "ignoredNames": [
      "chromeapp/**.*",
      "miBS/**.*"
    ],
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  },
  "dart-tools": {
    "dartSdkLocation": "c:\\dart\\dart-sdk\\bin"
  }
}
```

### Installed Packages

```coffee
# User
dart-tools, v0.9.2

# Dev
No dev packages
```

**Comment by radicaled** [comment]
Fixed in v0.9.3 ... probably.

**Comment by hectorfhurtado** [comment]
Hi, error doesn't appear anymore, but the package does nothing. It works great on Ubuntu tho.

**Comment by radicaled** [comment]
Can you summon the Command Palette (CTRL+SHIFT+P) and toggle the windows developer tools? I think it's "toggle dev" and then enter, not sure.

There should be a stacktrace or some words in the console, maybe.

**Comment by hectorfhurtado** [comment]
I'm digging and first I updated sdk-tools. Now I found that one need to append the extension like instead of running `dartSdk, bin, pub` the package needs to run `dartSdk, bin, pub.bat`. It works changing manually on lib/dart_tools.coffe file. After this change, It runs as intended.

Now I wonder if you have a config object for add these extensions: .exe for dart application and .bat for analyzer and pub

**Comment by radicaled** [comment]
Thanks for the investigation. I'm tracking it via #28!

**Comment by domesticmouse** [comment]
I triggered this issue on OSX by uninstalling my old dart sdk and installing a new one via brew install (at a different path) with version 0.9.23.

Let me know if there is some debugging data I can dig up from my install.

**Comment by radicaled** [comment]
Yeah, I don't think `dart-tools` handles the analysis_server going away very well.

This is fixed in https://github.com/dart-atom/dartlang which pretty much has everything `dart-tools` has at the moment.

**Comment by domesticmouse** [comment]
Thanks!

**Comment by darkn3rd** [comment]
I encountered this after installing `dartlang`.

**Comment by radicaled** [comment]
Make sure to uninstall this package after installing dartlang!
