### ISSUE TITLE
Uncaught TypeError: Promise resolver undefined is not a function

### ISSUE THREAD

**Issue by domesticmouse** [radicaled/dart-tools#27]
[Enter steps to reproduce below:]

1. Attempt to save a pubspec.yaml file for a project named 'untitled', based on commandline template

**Atom Version**: 0.199.0
**System**: Mac OS X 10.10.3
**Thrown From**: [dart-tools](https://github.com/radicaled/dart-tools) package, v0.9.4

### Stack Trace

Uncaught TypeError: Promise resolver undefined is not a function

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:759

TypeError: Promise resolver undefined is not a function
  at Formatter.module.exports.Formatter.formatEditor (/Users/brettmorgan/.atom/packages/dart-tools/lib/formatter.coffee:55:16)
  at Formatter.formatEditor (/Users/brettmorgan/.atom/packages/dart-tools/lib/formatter.coffee:1:1)
  at /Users/brettmorgan/.atom/packages/dart-tools/lib/formatter.coffee:81:8
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:917:20)
  at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:899:19)
  at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:567:26)
  at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:523:18)
  at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:506:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:585:35)
  at atom-workspace.atom.commands.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace-element.js:310:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:178:20)

```

### Commands

```
     -1:29.1.0 core:paste (atom-text-editor#dart-tools.dartSdkLocation.editor.mini.is-focused)
     -1:27.9.0 core:confirm (atom-text-editor#dart-tools.dartSdkLocation.editor.mini.is-focused)
  2x -1:09.4.0 core:save (atom-text-editor#dart-tools.dartSdkLocation.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "dart-tools": {
    "dartSdkLocation": "/usr/local/Cellar/dart/1.10.0/libexec"
  }
}
```

### Installed Packages

```coffee
# User
atom-dlang, v1.0.0
dart-tools, v0.9.4
git-log, v0.3.0
go-plus, v3.3.11
html-helper, v0.2.3
language-protobuf, v0.3.0
language-swift, v0.4.0
linter, v0.12.2
minimap, v4.8.0
slash-closer, v0.7.1

# Dev
No dev packages
```

**Comment by radicaled** [comment]
Thanks for the report!

Resolved in 0.9.5
