### ISSUE TITLE
Uncaught TypeError: Cannot read property 'formatEditor' of undefined

### ISSUE THREAD

**Issue by devoncarew** [radicaled/dart-tools#33]
[Enter steps to reproduce below:]

Running the dart format command.

**Atom Version**: 0.201.0
**System**: Mac OS X 10.9.5
**Thrown From**: [dart-tools](https://github.com/radicaled/dart-tools) package, v0.9.8

### Stack Trace

Uncaught TypeError: Cannot read property 'formatEditor' of undefined

```
At /Users/user/projects/dart-tools/lib/dart-tools.coffee:92

TypeError: Cannot read property 'formatEditor' of undefined
  at /Users/user/projects/dart-tools/lib/dart-tools.coffee:92:19
  at Function.module.exports.Utils.whenEditor (/Users/user/projects/dart-tools/lib/utils.coffee:23:5)
  at atom-workspace.<anonymous> (/Users/user/projects/dart-tools/lib/dart-tools.coffee:90:13)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/user/tools/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at __bind (/Users/user/tools/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Users/user/tools/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Users/user/tools/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.module.exports.SelectListView.initialize.atom.commands.add.core:confirm (/Users/user/tools/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/user/tools/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at __bind (/Users/user/tools/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Users/user/tools/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Users/user/tools/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Users/user/tools/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:178:20)

```

### Commands

```
     -1:24.9.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -1:21.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:21.3.0 dart-tools:sdk-info (atom-text-editor.editor)
     -0:59.5.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:50.4.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:45.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:45.2.0 dart-tools:pub-get (atom-text-editor.editor)
     -0:39 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-monokai.theme-atom-dark-ui)
  6x -0:36.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:22 dart-tools:toggle-analysis-view (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-monokai.theme-atom-dark-ui)
  2x -0:13.6.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  2x -0:01.3.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:00.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.6.0 dart-tools:format-code (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "disabledPackages": [
      "node-debugger",
      "atom-dart",
      "atom-sky",
      "sky-tools"
    ]
  },
  "dart-tools": {
    "dartSdkLocation": "/Users/user/homebrew/opt/dart/libexec",
    "pubGetOnSave": false,
    "formatOnSave": false
  }
}
```

### Installed Packages

```coffee
# User
dart-tools, v0.9.8
editorconfig, v1.0.0
monokai, v0.14.0

# Dev
No dev packages
```

**Comment by radicaled** [comment]
Fixed in v0.9.9
