### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by devoncarew** [radicaled/dart-tools#36]
[Enter steps to reproduce below:]

This occurs when starting Atom - see related PR.

**Atom Version**: 0.201.0
**System**: Mac OS X 10.9.5
**Thrown From**: [dart-tools](https://github.com/radicaled/dart-tools) package, v0.9.10

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/devoncarew/projects/dart-tools/lib/analysis/analysis_toolbar.coffee:33

TypeError: undefined is not a function
    at AnalysisToolbar.handleErrors (/Users/devoncarew/projects/dart-tools/lib/analysis/analysis_toolbar.coffee:39:24)
    at /Users/devoncarew/projects/dart-tools/lib/analysis/analysis_toolbar.coffee:3:61
    at Emitter.module.exports.Emitter.emit (/Users/devoncarew/projects/dart-tools/node_modules/event-kit/lib/emitter.js:82:11)
    at ErrorRepository.handleErrors (/Users/devoncarew/projects/dart-tools/lib/errors/error_repository.coffee:76:20)
    at /Users/devoncarew/projects/dart-tools/lib/errors/error_repository.coffee:3:61
    at Emitter.module.exports.Emitter.emit (/Users/devoncarew/projects/dart-tools/node_modules/event-kit/lib/emitter.js:82:11)
    at /Users/devoncarew/projects/dart-tools/lib/analysis_api.coffee:45:32
    at /Users/devoncarew/projects/dart-tools/lib/analysis_server.coffee:145:18
    at Emitter.module.exports.Emitter.emit (/Users/devoncarew/projects/dart-tools/node_modules/event-kit/lib/emitter.js:82:11)
    at AnalysisServer.module.exports.AnalysisServer.processMessage (/Users/devoncarew/projects/dart-tools/lib/analysis_server.coffee:119:22)
    at Stream.<anonymous> (/Users/devoncarew/projects/dart-tools/lib/analysis_server.coffee:3:61)
    at emitOne (events.js:77:13)
    at Stream.emit (events.js:166:7)
    at emitToken (/Users/devoncarew/projects/dart-tools/node_modules/stream-splitter/lib/splitter.js:23:21)
    at doSplit (/Users/devoncarew/projects/dart-tools/node_modules/stream-splitter/lib/splitter.js:29:9)
    at Stream.stream.write (/Users/devoncarew/projects/dart-tools/node_modules/stream-splitter/lib/splitter.js:46:7)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "disabledPackages": [
    ]
  },
  "dart-tools": {
    "dartSdkLocation": "/Users/devoncarew/homebrew/opt/dart/libexec",
    "pubGetOnSave": false,
    "formatOnSave": false
  }
}
```

### Installed Packages

```coffee
# User
dart-tools, v0.9.10
editorconfig, v1.0.0
monokai, v0.14.0

# Dev
No dev packages
```

**Comment by radicaled** [comment]
Are you editing the plugin in dev mode when you receive the error?

If so, go into your directory and do this:

`$ npm install`
`$ apm install`

And then restart Atom.

**Comment by devoncarew** [comment]
Yup, that fixed it -
